export const COLUMNS=[
    {Header:'Id',
    Footer:"Id",
     accessor:"id"},
    {Header:'Cases',
    Footer:"Cases",
    accessor:"Cases"},
    {Header:'Bezels',
    Footer:"Bezels",
    accessor:"Bezels"},
    {Header:'Bezel Inserts',
    Footer:"Bezel Inserts",
    accessor:"Bezel Inserts"},
    {Header:'Crowns',
    Footer:"Crowns",
    accessor:"Crowns"},
    {Header:'Dials',
    Footer:"Dials",
    accessor:"Dials"},
    {Header:'Hands',
    Footer:"Hands",
    accessor:"Hands"},
    {Header:'Chapter Rings',
    Footer:"Chapter Rings",
    accessor:"Chapter Rings"},
    {Header:'Straps',
    Footer:"Straps",
    accessor:"Straps"}

]
export const groupedColumns=[
    {Header:'Id',
Footer:'Id',
accessor:'id'},
    {Header:'Parts',
Footer:'Parts',
columns:[
    {Header:'Cases',
    Footer:"Cases",
    accessor:"Cases"},
    {Header:'Bezels',
    Footer:"Bezels",
    accessor:"Bezels"},
    {Header:'Bezel Inserts',
    Footer:"Bezel Inserts",
    accessor:"Bezel Inserts"},
    {Header:'Crowns',
    Footer:"Crowns",
    accessor:"Crowns"},
    {Header:'Dials',
    Footer:"Dials",
    accessor:"Dials"},
    {Header:'Hands',
    Footer:"Hands",
    accessor:"Hands"},
    {Header:'Chapter Rings',
    Footer:"Chapter Rings",
    accessor:"Chapter Rings"},
    {Header:'Straps',
    Footer:"Straps",
    accessor:"Straps"}
]}
]